### ISSUE TITLE
typo in README example

### ISSUE THREAD

**Issue by julibeg** [Vehmloewff/custom-format#3]
```
"editor.defaultFormatter": "vehmloewff.custom-format"
```
in the README should be 
```
"editor.defaultFormatter": "Vehmloewff.custom-format"
```
Otherwise, it won't work.

**Comment by Vehmloewff** [comment]
Thanks for the issue @julibeg.  I would be happy to accept a pull request for this :wink:

**Comment by julibeg** [comment]
Something else I just noticed, can `$FILE` still be used or does the command strictly need to read from STDIN?

**Comment by Vehmloewff** [comment]
The file content is passed to the stdin of the command after all instances of `$FILE` in that command are replaced with the absolute path of the file that is to be formatted.

**Comment by julibeg** [comment]
I'm not sure if I understand. I just tried with `"command": "head $FILE"` and that didn't do anything. The console says 
```
[error] Received an error while running the following format command on file.py:
> head $FILE
Error:
> Command failed with EPIPE: head file.py
> write EPIPE
```

**Comment by julibeg** [comment]
Also, have you ever used `sed` in one of these commands? I would like to use it with a quoted expression, but it gives an error.
Example: `"command": "sed s/# %%/blaaa/"` gives
```
[error] Received an error while running the following format command on file.py:
> sed 's/bla/bli/'
Error:
> Command failed with exit code 1: sed 's/bla/bli/'
> sed: -e expression #1, char 1: unknown command: `''
```

**Comment by Vehmloewff** [comment]
This sounds like some sort of issue - I'll have to take a look at it
