### ISSUE TITLE
Trailing newline is stripped

### ISSUE THREAD

**Issue by Minnozz** [Vehmloewff/custom-format#6]
I have configured [nixfmt](https://github.com/serokell/nixfmt) as a formatter for Nix files.

When I let nixfmt format either a file or stdin, the output always ends in a newline:
```console
$ echo -n '{}' | nixfmt | hexdump -C
00000000  7b 20 7d 0a                                       |{ }.|
00000004
```

However, when I format a Nix file in VSCode using custom-format, the trailing newline disappears:
```console
# Create a file with VSCode containing '{}' and format
$ hexdump -C test.nix
00000000  7b 20 7d                                          |{ }|
00000003
```

**Comment by Vehmloewff** [comment]
Hmm, interesting. Thanks for opening the issue @Minnozz. I don't have the bandwidth to investigate this issue right now. I would, however, be happy to accept a pull request that fixed this issue.

**Comment by Minnozz** [comment]
I have since discovered that the setting `"files.insertFinalNewline": true` fixes the problem for me, so the original behavior may not be caused by the extension but by VSCode itself.

**Comment by Vehmloewff** [comment]
Oh ok. Thank you for mentioning this @Minnozz. I am going to go ahead and close this issue, but if you find out more information later that points to this issue as not actually being resolved, just let me know and I will reopen.
