### ISSUE TITLE
Make it work with laravel/pint

### ISSUE THREAD

**Issue by bilogic** [Vehmloewff/custom-format#7]
Hi,

I was wondering if this extension can be adapted to work with https://github.com/laravel/pint
Pint outputs PASS/FAIL of its formatting instead of the formatted file. 

Can we have a configuration to read from formatted file instead of getting it from STDOUT? Or is there some limitation on VSCode side?

Thank you.

**Comment by Vehmloewff** [comment]
Hey @bilogic! You wouldn't want to format the file from/to disc with a VScode extension. If that is what you want to do, just use the `pint` command. The principal reason for this is that the version of the code in vscode won't be reflected on the disc if the editor is dirty.

To solve your particular use case, simply write a script that reads the STDIN, writes it to a temp file, runs `pint` on it, then prints the outputted file to STDOUT.

**Comment by bilogic** [comment]
@Vehmloewff thanks for getting back, yea that was what i did, and i did by modifying your plugin to create the temp file. Haha thanks!
